apiVersion: v1
kind: Service
metadata:
  name: {{ include "garrysmod.fullname" . }}
  labels:
    {{- include "garrysmod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: tcp
  selector:
    {{- include "garrysmod.selectorLabels" . | nindent 4 }}
